# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog de Codium
email: info@codium.team
description: >- # this means to ignore newlines until "baseurl:"
    Codium - Formamos y acompa침amos equipos de programaci칩n - Resultados, calidad y sostenibilidad
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.codium.team" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CodiumTeam
github_username:  CodiumTeam
timezone: 'Europe/Madrid'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:year-:month_:title

# Writer
nav_list:
    Blog : ['Home del Blog', '/', 'fa-book']
    Codium : ['Web de Codium', 'https://www.codium.team', 'fa-home']
    Valores : ['Valores de Codium', 'https://www.codium.team#values', 'fa-heart']
    Servicios : ['Servicios de Codium', 'https://www.codium.team#servicios', 'fa-star']
    TDD: ['Curso de TDD', 'https://www.codium.team/curso-tdd.html', 'fa-graduation-cap']
    LegacyCode : ['Curso de Legacy Code', 'https://www.codium.team/curso-legacy-code.html', 'fa-graduation-cap']
    Acompa침amiento : ['Acompa침amiento', 'https://www.codium.team/#acompanamiento', 'fa-users']
    MVP : ['Desarrollo de MVP', 'https://www.codium.team/#desarrollo', 'fa-gift']
    Equipo Codium : ['Equipo Codium', 'https://www.codium.team/#sobre-nosotros', 'fa-users']

single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
#footer_links:
#    About: ['About', '/about']
#    Writer: ['Writer 2016', '/about']


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
